apply plugin: 'java'
apply plugin: 'maven-publish'
repositories {
    jcenter()
    mavenCentral()
    google()
}

dependencies {
    implementation 'com.squareup.okhttp3:okhttp:3.14.2'
    implementation 'com.squareup.okhttp3:logging-interceptor:3.14.2'
    implementation 'com.fasterxml.jackson.core:jackson-databind:2.9.9'
    implementation 'org.slf4j:slf4j-api:1.7.26'
    implementation 'ch.qos.logback:logback-classic:1.2.3'

    testImplementation 'junit:junit:4.12'
}

publishing {
    publications {
        maven(MavenPublication) {
            groupId = 'endolabs.salesforce'
            artifactId = 'bulkv2'
            version = '1.0.0'
            from components.java
        }
    }
}
